Add metadata-convention-compliant metadata file (SCP-2832)
broadinstitute/single_cell_portal pull request #111
Opened 2020-10-19 19:12 UTC by jlchang

To improve metadata convention adoption, provide an example metadata-convention-compliant metadata file. This example file does not contain biosample_type (in anticipation of making biosample_type an optional metadata, SCP-2806 - to be completed this sprint), but has all other required metadata plus cell type and an example (non-convention) numeric annotation.

This satisfies SCP-2831.

2020-10-19 19:22 UTC, devonbush approved these changes

2020-10-19 19:34 UTC, eweitz requested changes
Content looks good, but please add "metadata" somewhere in the file name, e.g. perhaps `mc_compliant_metadata_example.txt`.  That will help users (and us) recall at a glance what this file is for.

2020-10-20 18:12 UTC, jlchang commented
> Content looks good, but please add "metadata" somewhere in the file name, e.g. perhaps `mc_compliant_metadata_example.txt`. That will help users (and us) recall at a glance what this file is for.

Updated file name in `c728f23`. Thanks for the suggestion!

2020-10-22 14:49 UTC, eweitz approved these changes

2020-10-23 17:33 UTC, knapii-developments approved these changes

2020-10-28 17:17 UTC, merged